<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>files</key>
	<dict>
		<key>Headers/EGL/egl.h</key>
		<data>
		ErK2VQcIbRW+xdkdNMGy1lQ23Co=
		</data>
		<key>Headers/EGL/eglext.h</key>
		<data>
		J5Dec6J2qTf02e2W2MUeEwmJ4KI=
		</data>
		<key>Headers/EGL/eglext_angle.h</key>
		<data>
		L0+JZl6akpSt7lvZar20RSX5qLY=
		</data>
		<key>Headers/EGL/eglplatform.h</key>
		<data>
		/3rTFUhi1cGXOFi8IBKoiHHhDaM=
		</data>
		<key>Headers/GLES2/gl2.h</key>
		<data>
		gkOvFIWUYOszv8kzaH3IOI+rDTs=
		</data>
		<key>Headers/GLES2/gl2ext.h</key>
		<data>
		Do9fhQ9lyFn69WH4SVqD7NE7cDA=
		</data>
		<key>Headers/GLES2/gl2platform.h</key>
		<data>
		ObI3LD0lSt3uQHaC9EdgyiIRbH4=
		</data>
		<key>Headers/GLES3/gl3.h</key>
		<data>
		AKEvk9qSydDR39CELH/PwHB3NAQ=
		</data>
		<key>Headers/GLES3/gl31.h</key>
		<data>
		65BBHtcUrMaEwiXhrn0xBeagqeM=
		</data>
		<key>Headers/GLES3/gl32.h</key>
		<data>
		RMwPh4o+75KfvFdv97nmFOAFo1E=
		</data>
		<key>Headers/GLES3/gl3ext.h</key>
		<data>
		RmPGeZcRJD6bW2SsvRPbcfIJHqw=
		</data>
		<key>Headers/GLES3/gl3platform.h</key>
		<data>
		oDL7vQepD9N4oVSDTT3GzpPuGY0=
		</data>
		<key>Headers/KHR/khrplatform.h</key>
		<data>
		6HcmkbIdfNZ7Z67r2FOnAhKU0P0=
		</data>
		<key>Headers/MGLContext.h</key>
		<data>
		AHhM0TTIrmquGmgfcLFJx0xpSfo=
		</data>
		<key>Headers/MGLDisplay.h</key>
		<data>
		rofQDN5l1KenqkOPTdEk9PDo0Ds=
		</data>
		<key>Headers/MGLKView.h</key>
		<data>
		/aLhxKCqWPuFMOr9VxS9V7UXOVE=
		</data>
		<key>Headers/MGLKViewController.h</key>
		<data>
		qJRzdpMfV5V/QWQCD1RbgZ/LclA=
		</data>
		<key>Headers/MGLKit.h</key>
		<data>
		NeFTeFk/Cf0G7BFFey9towoHIBQ=
		</data>
		<key>Headers/MGLKitPlatform.h</key>
		<data>
		lNfQ16xsVuy5s2rGMHlX4984apU=
		</data>
		<key>Headers/MGLLayer.h</key>
		<data>
		tUAgx3RyS/V0jjFseIH+8SQfpcw=
		</data>
		<key>Headers/angle_gl.h</key>
		<data>
		6dvzxwRtDaTbwBVWH4MyQaejCPM=
		</data>
		<key>Headers/export.h</key>
		<data>
		IjA9wikEb8dIA8+3PLKbeHu7gyM=
		</data>
		<key>Info.plist</key>
		<data>
		VK8RRNOzPsSQ5pQICpdYzUWFWnc=
		</data>
	</dict>
	<key>files2</key>
	<dict>
		<key>Headers/EGL/egl.h</key>
		<dict>
			<key>hash2</key>
			<data>
			h7PYYEGcioB7z+hrSKkzSayc00ohPI4zkUhAMDYx/oc=
			</data>
		</dict>
		<key>Headers/EGL/eglext.h</key>
		<dict>
			<key>hash2</key>
			<data>
			NJbCIYu9gTt5MjaUCZk4VkSqrZoxfoa2spZk4R8yYtQ=
			</data>
		</dict>
		<key>Headers/EGL/eglext_angle.h</key>
		<dict>
			<key>hash2</key>
			<data>
			aw+dNSb0kqYffk8E5cJ0Tes9Ujj555HLW0MfT39v8dQ=
			</data>
		</dict>
		<key>Headers/EGL/eglplatform.h</key>
		<dict>
			<key>hash2</key>
			<data>
			wp+7Y2MoxXGMWq3/GG0jQAAouUU2QXRuBJsvIqnUDfU=
			</data>
		</dict>
		<key>Headers/GLES2/gl2.h</key>
		<dict>
			<key>hash2</key>
			<data>
			NJHboGDO3/AJAUFBpQcDCxNrmZsJkmoHCOUyP89+0cc=
			</data>
		</dict>
		<key>Headers/GLES2/gl2ext.h</key>
		<dict>
			<key>hash2</key>
			<data>
			YM53jY5sFbmFWN+Kwzfkz+st5GnrwajoMAFwIPWgpCQ=
			</data>
		</dict>
		<key>Headers/GLES2/gl2platform.h</key>
		<dict>
			<key>hash2</key>
			<data>
			9doHR1QKUL5fRKrSZKrkW98VehksQPF0h92aL5nHG2w=
			</data>
		</dict>
		<key>Headers/GLES3/gl3.h</key>
		<dict>
			<key>hash2</key>
			<data>
			hwdZYp5L3WUngtmxZEdpE4667D8UKHCT/NuRjE9xfFM=
			</data>
		</dict>
		<key>Headers/GLES3/gl31.h</key>
		<dict>
			<key>hash2</key>
			<data>
			YS/Do8SDuqOwTfpr48tEIXrV67ksOvBVMdysLBWbF3o=
			</data>
		</dict>
		<key>Headers/GLES3/gl32.h</key>
		<dict>
			<key>hash2</key>
			<data>
			5YDn22v8a4aGCuawL6J+uaz+Zya6tx+cJoVozb+Auuo=
			</data>
		</dict>
		<key>Headers/GLES3/gl3ext.h</key>
		<dict>
			<key>hash2</key>
			<data>
			VzDakCzsBLhvkxUqIZs3nqu/TqyXOH8nH7gUH9/kxcU=
			</data>
		</dict>
		<key>Headers/GLES3/gl3platform.h</key>
		<dict>
			<key>hash2</key>
			<data>
			qeBg2uWisRxaiJtnlpK3CJoQp+A+v7ts8oIX9uMi+wg=
			</data>
		</dict>
		<key>Headers/KHR/khrplatform.h</key>
		<dict>
			<key>hash2</key>
			<data>
			ebvJDcPY2X7H2CtY2uY2OU/ou0bWuJ4SetK2zQI5pr4=
			</data>
		</dict>
		<key>Headers/MGLContext.h</key>
		<dict>
			<key>hash2</key>
			<data>
			69fEBBimTpmHZfi9SCDtlvKnFoaWoTbbUPsW2VefUxU=
			</data>
		</dict>
		<key>Headers/MGLDisplay.h</key>
		<dict>
			<key>hash2</key>
			<data>
			QVfmCA0CTaQshoX42Zwe2xQsiIC3lIWIn7t1Uuwspbw=
			</data>
		</dict>
		<key>Headers/MGLKView.h</key>
		<dict>
			<key>hash2</key>
			<data>
			SL4e9UixBYlMYMMA7c8MNUWBBRY01iSMNmr+qvMaxgY=
			</data>
		</dict>
		<key>Headers/MGLKViewController.h</key>
		<dict>
			<key>hash2</key>
			<data>
			uzj/4mbvwQCmdm0/cqA2yK/AENx0MPd9X8qAhfqtGjA=
			</data>
		</dict>
		<key>Headers/MGLKit.h</key>
		<dict>
			<key>hash2</key>
			<data>
			aAUFzJBIKCb26hltpkmwnkvClkR/VUN7/kG9t4561fg=
			</data>
		</dict>
		<key>Headers/MGLKitPlatform.h</key>
		<dict>
			<key>hash2</key>
			<data>
			NlmIBoFnbpGB4/8KbQ5AYtDSJ6q0eGeO0kEyF3nbedg=
			</data>
		</dict>
		<key>Headers/MGLLayer.h</key>
		<dict>
			<key>hash2</key>
			<data>
			ZgsXYhkA68OO10ryinrK2XgNS9SoVcq60WMfVmMkn5g=
			</data>
		</dict>
		<key>Headers/angle_gl.h</key>
		<dict>
			<key>hash2</key>
			<data>
			iU60xZfCsYbS7Ec2gKmD1Rv8gy+P6gbbBaitdcB7Syo=
			</data>
		</dict>
		<key>Headers/export.h</key>
		<dict>
			<key>hash2</key>
			<data>
			xwE4yp1zdzZdbzwEmDdvGynSDTuM2AIVhOB+8KpSPz0=
			</data>
		</dict>
	</dict>
	<key>rules</key>
	<dict>
		<key>^.*</key>
		<true/>
		<key>^.*\.lproj/</key>
		<dict>
			<key>optional</key>
			<true/>
			<key>weight</key>
			<real>1000</real>
		</dict>
		<key>^.*\.lproj/locversion.plist$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>1100</real>
		</dict>
		<key>^Base\.lproj/</key>
		<dict>
			<key>weight</key>
			<real>1010</real>
		</dict>
		<key>^version.plist$</key>
		<true/>
	</dict>
	<key>rules2</key>
	<dict>
		<key>.*\.dSYM($|/)</key>
		<dict>
			<key>weight</key>
			<real>11</real>
		</dict>
		<key>^(.*/)?\.DS_Store$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>2000</real>
		</dict>
		<key>^.*</key>
		<true/>
		<key>^.*\.lproj/</key>
		<dict>
			<key>optional</key>
			<true/>
			<key>weight</key>
			<real>1000</real>
		</dict>
		<key>^.*\.lproj/locversion.plist$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>1100</real>
		</dict>
		<key>^Base\.lproj/</key>
		<dict>
			<key>weight</key>
			<real>1010</real>
		</dict>
		<key>^Info\.plist$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>20</real>
		</dict>
		<key>^PkgInfo$</key>
		<dict>
			<key>omit</key>
			<true/>
			<key>weight</key>
			<real>20</real>
		</dict>
		<key>^embedded\.provisionprofile$</key>
		<dict>
			<key>weight</key>
			<real>20</real>
		</dict>
		<key>^version\.plist$</key>
		<dict>
			<key>weight</key>
			<real>20</real>
		</dict>
	</dict>
</dict>
</plist>
